name: "01 -  simple exemple"

on: push

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps:
      - name: "Afficher des infos"
        run: |
          echo "Push detecte"
          echo "Author : ${{ github.actor }}"
          echo "Branche : ${{ github.ref_name }}"
          echo "Sha : ${{ github.sha }}"
  