name: "02 -  push filtre branches"

on:
  push:
    branches:
      - main
      - develop

jobs:
  afficher-info:
    runs-on: ubuntu-latest
    steps:
      - name: "Afficher des infos"
        run: |
          echo "Branche detecte"
          echo "Branche : ${{ github.ref_name }}"